---
collections:
  - name: ansible.posix
    source: https://galaxy.ansible.com
  - name: ansible.utils
    source: https://galaxy.ansible.com
  - name: kubernetes.core
    source: https://galaxy.ansible.com
  - name: infra.openshift_virtualization_migration
    source: https://console.redhat.com/api/automation-hub/content/validated/