---
collections:
  - name: amazon.aws
  - name: community.postgresql
  - name: kubernetes.core
  - name: ansible.posix
  - name: ansible.utils
  - name: infra.openshift_virtualization_migration
  - name: awx.awx